<a href="https://colab.research.google.com/github/prekhanshi/Experiment_No_14_Data_Nomalization_And_Types/blob/main/exp14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Name: Prekhanshi kumbhhakar
#PRN: 25070123151
#branch: ENTC
#batch: A1
#EXPERIMENT NO. 14
#TITLE: Data Normalization and its types
#date: 31/03/26

In [ ]:
#dataset
import pandas as pd
import numpy as np

data = {
    'product': [ 'laptop','mobile', 'tablet','headphones','smartwatch','camera' ],
    'price' : [55000,20000,30000,2000,8000,45000],
    'units_sold': [25,60,35,80,50,15],
    'discount': [10,15,12,20,18,8]
}
df = pd.DataFrame(data)
print(df)

      product  price  units_sold  discount
0      laptop  55000          25        10
1      mobile  20000          60        15
2      tablet  30000          35        12
3  headphones   2000          80        20
4  smartwatch   8000          50        18
5      camera  45000          15         8

In [ ]:
#1.min-max normalization
# min max normalization for price
df['price_MinMax'] = (df['price'] - df['price'].min()) / (df['price'].max() - df['price'].min())
print("\nMin-Max Normalized Data:")
print(df[['product','price','price_MinMax']])

Min-Max Normalized Data:
      product  price  price_MinMax
0      laptop  55000      1.000000
1      mobile  20000      0.339623
2      tablet  30000      0.528302
3  headphones   2000      0.000000
4  smartwatch   8000      0.113208
5      camera  45000      0.811321

In [ ]:
#normalize multiple columns
cols = ['price','units_sold','discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print ('\nNormalized Dataset')
print(df_norm)

Normalized Dataset
      price  units_sold  discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
#2. Z score normalization
df['units_zscore'] = (df['units_sold'] - df['units_sold'].mean()) / df['units_sold'].std()
print("\nZ-Score Normalized units sold:")
print(df[['product','units_sold','units_zscore']])

Z-Score Normalized units sold:
      product  units_sold  units_zscore
0      laptop          25     -0.799885
1      mobile          60      0.660775
2      tablet          35     -0.382554
3  headphones          80      1.495437
4  smartwatch          50      0.243443
5      camera          15     -1.217216

In [ ]:
#3. decimal scaling
df['price_decimal'] = df['price']/ 100000
print('\ndecimal scaling')
print(df[['product', 'price', 'price_decimal']])

decimal scaling
      product  price  price_decimal
0      laptop  55000           0.55
1      mobile  20000           0.20
2      tablet  30000           0.30
3  headphones   2000           0.02
4  smartwatch   8000           0.08
5      camera  45000           0.45

In [ ]:
#data nromalization
import pandas as pd
df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')
print(df)

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# min max normalization
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max()
- df['Price'].min())
print("\nMin-Max Normalized Data:")
print(df[['Product_Name','Price','Price_MinMax']])

Min-Max Normalized Data:
                   Product_Name  Price  Price_MinMax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

In [ ]:
cols = ['Price','Rating','Reviews','Units_Sold']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print ('\nNormalized Dataset')
print(df_norm)

Normalized Dataset
       Price    Rating   Reviews  Units_Sold
0   0.020243  0.428571  0.291005    0.518519
1   0.048583  0.714286  0.148148    0.277778
2   0.016194  0.142857  0.119048    0.203704
3   0.089069  0.857143  0.444444    0.629630
4   0.149798  0.571429  0.695767    0.833333
5   0.036437  0.285714  0.351852    0.592593
6   0.024291  0.000000  0.052910    0.129630
7   0.064777  0.428571  0.185185    0.351852
8   0.210526  1.000000  0.378307    0.481481
9   0.028340  0.285714  0.089947    0.222222
10  0.311741  0.857143  1.000000    1.000000
11  0.174089  0.714286  0.444444    0.407407
12  0.052632  0.571429  0.232804    0.500000
13  0.016194  0.142857  0.031746    0.092593
14  0.024291  0.285714  0.119048    0.240741
15  0.251012  0.857143  0.497354    0.444444
16  0.036437  0.428571  0.089947    0.259259
17  0.068826  0.571429  0.312169    0.648148
18  0.109312  0.714286  0.814815    0.851852
19  0.040486  0.428571  0.148148    0.351852
20  0.008097  0.000000  0.000000    0.148148
21  0.089069  0.571429  0.272487    0.444444
22  0.352227  0.857143  0.219577    0.185185
23  0.020243  0.285714  0.079365    0.259259
24  0.129555  0.714286  0.444444    0.592593
25  0.174089  0.571429  0.148148    0.166667
26  0.514170  1.000000  0.708995    0.129630
27  0.076923  0.428571  0.232804    0.370370
28  0.016194  0.285714  0.121693    0.314815
29  0.048583  0.428571  0.150794    0.351852
30  0.392713  0.857143  0.444444    0.240741
31  0.230769  0.714286  0.351852    0.203704
32  0.129555  0.571429  0.550265    0.666667
33  0.473684  0.857143  0.272487    0.092593
34  0.635628  1.000000  0.444444    0.037037
35  0.012146  0.142857  0.007937    0.166667
36  0.020243  0.285714  0.126984    0.462963
37  0.000000  0.000000  0.047619    0.574074
38  0.028340  0.428571  0.079365    0.259259
39  0.048583  0.571429  0.026455    0.111111
40  0.109312  0.714286  0.113757    0.148148
41  0.433198  0.857143  0.206349    0.074074
42  0.190283  0.571429  0.444444    0.351852
43  1.000000  1.000000  0.365079    0.000000
44  0.068826  0.428571  0.259259    0.444444
45  0.311741  0.857143  0.470899    0.240741
46  0.757085  0.714286  0.325397    0.092593
47  0.089069  0.571429  0.148148    0.185185
48  0.129555  0.428571  0.119048    0.148148
49  0.028340  0.285714  0.089947    0.314815

In [ ]:
#Z score normalization
df['Rating_zscore'] = (df['Rating'] - df['Rating'].mean()) / df['Rating'].std()
print("\nZ-Score Normalized Rating:")
print(df[['Product_Name','Rating','Rating_zscore']])

Z-Score Normalized Rating:
                   Product_Name  Rating  Rating_zscore
0                Wireless Mouse     4.3      -0.421580
1             Bluetooth Speaker     4.5       0.606665
2                  USB Keyboard     4.1      -1.449825
3                Gaming Headset     4.6       1.120787
4                    Smartwatch     4.4       0.092542
5                    Power Bank     4.2      -0.935703
6                  Laptop Stand     4.0      -1.963948
7                        Webcam     4.3      -0.421580
8                  Portable SSD     4.7       1.634910
9              Wireless Charger     4.2      -0.935703
10  Noise Cancelling Headphones     4.6       1.120787
11          Mechanical Keyboard     4.5       0.606665
12                 Gaming Mouse     4.4       0.092542
13                 Tablet Stand     4.1      -1.449825
14                      USB Hub     4.2      -0.935703
15          External Hard Drive     4.6       1.120787
16            Smartphone Tripod     4.3      -0.421580
17              Laptop Backpack     4.4       0.092542
18            Bluetooth Earbuds     4.5       0.606665
19                LED Desk Lamp     4.3      -0.421580
20                 Phone Holder     4.0      -1.963948
21            Wireless Keyboard     4.4       0.092542
22             Portable Monitor     4.6       1.120787
23                   Smart Plug     4.2      -0.935703
24                  WiFi Router     4.5       0.606665
25              Graphics Tablet     4.4       0.092542
26                   VR Headset     4.7       1.634910
27                   Microphone     4.3      -0.421580
28             Smart Light Bulb     4.2      -0.935703
29           Laptop Cooling Pad     4.3      -0.421580
30                Action Camera     4.6       1.120787
31               Smart Doorbell     4.5       0.606665
32              Streaming Stick     4.4       0.092542
33           Portable Projector     4.6       1.120787
34                 Gaming Chair     4.7       1.634910
35               Desk Organizer     4.1      -1.449825
36              USB Flash Drive     4.2      -0.935703
37       Phone Screen Protector     4.0      -1.963948
38                Laptop Sleeve     4.3      -0.421580
39           Wireless Presenter     4.4       0.092542
40         Tablet Keyboard Case     4.5       0.606665
41             Smart Thermostat     4.6       1.120787
42              Security Camera     4.4       0.092542
43                 Drone Camera     4.7       1.634910
44              Electric Kettle     4.3      -0.421580
45                    Air Fryer     4.6       1.120787
46                 Robot Vacuum     4.5       0.606665
47                  Smart Scale     4.4       0.092542
48          Digital Photo Frame     4.3      -0.421580
49                 Portable Fan     4.2      -0.935703

In [ ]:
# decimal scaling
df['Price_decimal'] = df['Price']/ 100000
print('\ndecimal scaling')
print(df)

decimal scaling
   Product_ID                 Product_Name  Price  Rating  Reviews  \
0        P101               Wireless Mouse    799     4.3     1520
1        P102            Bluetooth Speaker   1499     4.5      980
2        P103                 USB Keyboard    699     4.1      870
3        P104               Gaming Headset   2499     4.6     2100
4        P105                   Smartwatch   3999     4.4     3050
5        P106                   Power Bank   1199     4.2     1750
6        P107                 Laptop Stand    899     4.0      620
7        P108                       Webcam   1899     4.3     1120
8        P109                 Portable SSD   5499     4.7     1850
9        P110             Wireless Charger    999     4.2      760
10       P111  Noise Cancelling Headphones   7999     4.6     4200
11       P112          Mechanical Keyboard   4599     4.5     2100
12       P113                 Gaming Mouse   1599     4.4     1300
13       P114                 Tablet Stand    699     4.1      540
14       P115                      USB Hub    899     4.2      870
15       P116          External Hard Drive   6499     4.6     2300
16       P117            Smartphone Tripod   1199     4.3      760
17       P118              Laptop Backpack   1999     4.4     1600
18       P119            Bluetooth Earbuds   2999     4.5     3500
19       P120                LED Desk Lamp   1299     4.3      980
20       P121                 Phone Holder    499     4.0      420
21       P122            Wireless Keyboard   2499     4.4     1450
22       P123             Portable Monitor   8999     4.6     1250
23       P124                   Smart Plug    799     4.2      720
24       P125                  WiFi Router   3499     4.5     2100
25       P126              Graphics Tablet   4599     4.4      980
26       P127                   VR Headset  12999     4.7     3100
27       P128                   Microphone   2199     4.3     1300
28       P129             Smart Light Bulb    699     4.2      880
29       P130           Laptop Cooling Pad   1499     4.3      990
30       P131                Action Camera   9999     4.6     2100
31       P132               Smart Doorbell   5999     4.5     1750
32       P133              Streaming Stick   3499     4.4     2500
33       P134           Portable Projector  11999     4.6     1450
34       P135                 Gaming Chair  15999     4.7     2100
35       P136               Desk Organizer    599     4.1      450
36       P137              USB Flash Drive    799     4.2      900
37       P138       Phone Screen Protector    299     4.0      600
38       P139                Laptop Sleeve    999     4.3      720
39       P140           Wireless Presenter   1499     4.4      520
40       P141         Tablet Keyboard Case   2999     4.5      850
41       P142             Smart Thermostat  10999     4.6     1200
42       P143              Security Camera   4999     4.4     2100
43       P144                 Drone Camera  24999     4.7     1800
44       P145              Electric Kettle   1999     4.3     1400
45       P146                    Air Fryer   7999     4.6     2200
46       P147                 Robot Vacuum  18999     4.5     1650
47       P148                  Smart Scale   2499     4.4      980
48       P149          Digital Photo Frame   3499     4.3      870
49       P150                 Portable Fan    999     4.2      760

    Units_Sold  Price_MinMax  Rating_zscore  Price_decimal
0          350      0.020243      -0.421580        0.00799
1          220      0.048583       0.606665        0.01499
2          180      0.016194      -1.449825        0.00699
3          410      0.089069       1.120787        0.02499
4          520      0.149798       0.092542        0.03999
5          390      0.036437      -0.935703        0.01199
6          140      0.024291      -1.963948        0.00899
7          260      0.064777      -0.421580        0.01899
8          330      0.210526       1.634910        0.05499
9          190      0.028340      -0.935703        0.00999
10         610      0.311741       1.120787        0.07999
11         290      0.174089       0.606665        0.04599
12         340      0.052632       0.092542        0.01599
13         120      0.016194      -1.449825        0.00699
14         200      0.024291      -0.935703        0.00899
15         310      0.251012       1.120787        0.06499
16         210      0.036437      -0.421580        0.01199
17         420      0.068826       0.092542        0.01999
18         530      0.109312       0.606665        0.02999
19         260      0.040486      -0.421580        0.01299
20         150      0.008097      -1.963948        0.00499
21         310      0.089069       0.092542        0.02499
22         170      0.352227       1.120787        0.08999
23         210      0.020243      -0.935703        0.00799
24         390      0.129555       0.606665        0.03499
25         160      0.174089       0.092542        0.04599
26         140      0.514170       1.634910        0.12999
27         270      0.076923      -0.421580        0.02199
28         240      0.016194      -0.935703        0.00699
29         260      0.048583      -0.421580        0.01499
30         200      0.392713       1.120787        0.09999
31         180      0.230769       0.606665        0.05999
32         430      0.129555       0.092542        0.03499
33         120      0.473684       1.120787        0.11999
34          90      0.635628       1.634910        0.15999
35         160      0.012146      -1.449825        0.00599
36         320      0.020243      -0.935703        0.00799
37         380      0.000000      -1.963948        0.00299
38         210      0.028340      -0.421580        0.00999
39         130      0.048583       0.092542        0.01499
40         150      0.109312       0.606665        0.02999
41         110      0.433198       1.120787        0.10999
42         260      0.190283       0.092542        0.04999
43          70      1.000000       1.634910        0.24999
44         310      0.068826      -0.421580        0.01999
45         200      0.311741       1.120787        0.07999
46         120      0.757085       0.606665        0.18999
47         170      0.089069       0.092542        0.02499
48         150      0.129555      -0.421580        0.03499
49         240      0.028340      -0.935703        0.00999

In [ ]:
# part B: turning categorical variables into quantitative variables
import pandas as pd
data= {
'Order_ID' : [101,182,283,204,105,106],
'Customer _Gender': ['Male','Female', 'Female', 'Male', 'Female', 'Male'],
"Payment_Method" : ["UPI", 'Credit Card', 'Debit Card', 'COD', 'UPI', 'Debit Card'],
'Product _Category': ['Electronics', 'Clothing', 'Home', 'Electronics', 'Beauty', 'Electronics'],
"City": ['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Hyderabad'],
"Order _Value" : [4509,2388,3288,5208,1800,4108]
}
df = pd.DataFrame(data)
df

,Order_ID,Customer _Gender,Payment_Method,Product _Category,City,Order _Value
0,101,Male,UPI,Electronics,Pune,4509
1,182,Female,Credit Card,Clothing,Mumbai,2388
2,283,Female,Debit Card,Home,Delhi,3288
3,204,Male,COD,Electronics,Bangalore,5208
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Electronics,Hyderabad,4108

In [ ]:
# method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer _Gender'])
df

,Order_ID,Customer _Gender,Payment_Method,Product _Category,City,Order _Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4509,1
1,182,Female,Credit Card,Clothing,Mumbai,2388,0
2,283,Female,Debit Card,Home,Delhi,3288,0
3,204,Male,COD,Electronics,Bangalore,5208,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electronics,Hyderabad,4108,1

In [ ]:
#method 2: one hot encodng
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])
df_encoded

,Order_ID,Customer _Gender,Product _Category,City,Order _Value,Gender_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4509,1,False,False,False,True
1,182,Female,Clothing,Mumbai,2388,0,False,True,False,False
2,283,Female,Home,Delhi,3288,0,False,False,True,False
3,204,Male,Electronics,Bangalore,5208,1,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,False,False,False,True
5,106,Male,Electronics,Hyderabad,4108,1,False,False,True,False

In [ ]:
#method 3: encoding multiple columns
df_multi = pd.get_dummies(df, columns=['Product _Category','City'])
print(df_multi)

   Order_ID Customer _Gender Payment_Method  Order _Value  Gender_Label  \
0       101             Male            UPI          4509             1
1       182           Female    Credit Card          2388             0
2       283           Female     Debit Card          3288             0
3       204             Male            COD          5208             1
4       105           Female            UPI          1800             0
5       106             Male     Debit Card          4108             1

   Product _Category_Beauty  Product _Category_Clothing  \
0                     False                       False
1                     False                        True
2                     False                       False
3                     False                       False
4                      True                       False
5                     False                       False

   Product _Category_Electronics  Product _Category_Home  City_Bangalore  \
0                           True                   False           False
1                          False                   False           False
2                          False                    True           False
3                           True                   False            True
4                          False                   False           False
5                           True                   False           False

   City_Delhi  City_Hyderabad  City_Mumbai  City_Pune
0       False           False        False       True
1       False           False         True      False
2        True           False        False      False
3       False           False        False      False
4       False           False        False       True
5       False            True        False      False

In [ ]:
#Method 3: dummy encoding (drop first)
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
print(df_dummy)

   Order_ID Customer _Gender Product _Category       City  Order _Value  \
0       101             Male       Electronics       Pune          4509
1       182           Female          Clothing     Mumbai          2388
2       283           Female              Home      Delhi          3288
3       204             Male       Electronics  Bangalore          5208
4       105           Female            Beauty       Pune          1800
5       106             Male       Electronics  Hyderabad          4108

   Gender_Label  Payment_Method_Credit Card  Payment_Method_Debit Card  \
0             1                       False                      False
1             0                        True                      False
2             0                       False                       True
3             1                       False                      False
4             0                       False                      False
5             1                       False                       True

   Payment_Method_UPI
0                True
1               False
2               False
3               False
4                True
5               False

In [ ]:
# part C
import pandas as pd
df = pd.read_csv('/content/Student-Dataset.csv')
print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary
0                     92           Placed  450000
1                     85       Not Placed       0
2                     96           Placed  550000
3                     78       Not Placed       0
4                     88           Placed  480000
5                     72       Not Placed       0
6                     91           Placed  500000
7                     80       Not Placed       0
8                     84           Placed  420000
9                     76       Not Placed       0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Gender'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,0
1,102,Male,IT,7.5,1,85,Not Placed,0,1
2,103,Female,ENTC,9.1,0,96,Placed,550000,0
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1
4,105,Female,Computer,8.7,0,88,Placed,480000,0
5,106,Male,Civil,7.2,3,72,Not Placed,0,1
6,107,Female,IT,8.9,0,91,Placed,500000,0
7,108,Male,Computer,6.5,1,80,Not Placed,0,1
8,109,Female,ENTC,7.8,0,84,Placed,420000,0
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1

In [ ]:
#method 2: one hot encodng
df_encoded = pd.get_dummies(df, columns=['Department'])
df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,0,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,1,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,0,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,1,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,0,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,1,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,0,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,1,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,0,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,1,False,False,False,False,True

In [ ]:
#method 3: encoding multiple columns
df_multi = pd.get_dummies(df, columns=['Placement_Status','Salary'])
print(df_multi)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage  Gender_Label  Placement_Status_Not Placed  \
0                     92             0                        False
1                     85             1                         True
2                     96             0                        False
3                     78             1                         True
4                     88             0                        False
5                     72             1                         True
6                     91             0                        False
7                     80             1                         True
8                     84             0                        False
9                     76             1                         True

   Placement_Status_Placed  Salary_0  Salary_420000  Salary_450000  \
0                     True     False          False           True
1                    False      True          False          False
2                     True     False          False          False
3                    False      True          False          False
4                     True     False          False          False
5                    False      True          False          False
6                     True     False          False          False
7                    False      True          False          False
8                     True     False           True          False
9                    False      True          False          False

   Salary_480000  Salary_500000  Salary_550000
0          False          False          False
1          False          False          False
2          False          False           True
3          False          False          False
4           True          False          False
5          False          False          False
6          False           True          False
7          False          False          False
8          False          False          False
9          False          False          False